sample_products = [
    {
        "product_id": "1",
        "name": "Wireless Earbuds",
        "description": "Bluetooth 5.0 earbuds with noise cancellation and 24-hour battery life.",
        "category": "Electronics",
        "price": 59.99,
        "stock_quantity": 120,
    },
    {
        "product_id": "2",
        "name": "4K LED Smart TV",
        "description": "55-inch Ultra HD TV with streaming apps and voice control.",
        "category": "Electronics",
        "price": 499.99,
        "stock_quantity": 45,
    },
    {
        "product_id": "3",
        "name": "Gaming Laptop",
        "description": "15.6-inch gaming laptop with Intel i7 processor, 16GB RAM, and NVIDIA GTX 1660 Ti.",
        "category": "Computers",
        "price": 1099.99,
        "stock_quantity": 25,
    },
    {
        "product_id": "4",
        "name": "Running Shoes",
        "description": "Breathable running shoes with cushioned sole and durable design.",
        "category": "Sportswear",
        "price": 89.99,
        "stock_quantity": 200,
    },
    {
        "product_id": "5",
        "name": "Stainless Steel Water Bottle",
        "description": "Insulated water bottle with 24-hour cold retention and 12-hour heat retention.",
        "category": "Home & Kitchen",
        "price": 24.99,
        "stock_quantity": 300,
    },
    {
        "product_id": "6",
        "name": "Wooden Dining Table",
        "description": "6-seater dining table made from high-quality oak wood.",
        "category": "Furniture",
        "price": 749.99,
        "stock_quantity": 10,
    },
    {
        "product_id": "7",
        "name": "Noise Cancelling Headphones",
        "description": "Over-ear headphones with active noise cancellation and 30-hour battery life.",
        "category": "Electronics",
        "price": 299.99,
        "stock_quantity": 60,
    },
    {
        "product_id": "8",
        "name": "Yoga Mat",
        "description": "Eco-friendly, non-slip yoga mat with 6mm thickness for extra cushioning.",
        "category": "Fitness",
        "price": 39.99,
        "stock_quantity": 150,
    },
    {
        "product_id": "9",
        "name": "Smartphone",
        "description": "Latest model smartphone with 6.5-inch display, 128GB storage, and triple camera system.",
        "category": "Electronics",
        "price": 799.99,
        "stock_quantity": 35,
    },
    {
        "product_id": "10",
        "name": "Leather Wallet",
        "description": "Genuine leather wallet with RFID blocking and multiple card slots.",
        "category": "Accessories",
        "price": 49.99,
        "stock_quantity": 85,
    },
]
